### ISSUE TITLE
Crashes ReviewBoard 2.5.2

### ISSUE THREAD

**Issue by vladsf** [iconoeugen/rb-xmpp-notification#7]
Traceback (most recent call last):

 File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
   response = middleware_method(request)

 File "/usr/lib/python2.7/site-packages/reviewboard/admin/middleware.py", line 34, in process_request
   initialize()

 File "/usr/lib/python2.7/site-packages/reviewboard/**init**.py", line 147, in initialize
   get_extension_manager().load()

 File "/usr/lib/python2.7/site-packages/djblets/extensions/manager.py", line 416, in load
   self._load_extensions(full_reload)

 File "/usr/lib/python2.7/site-packages/djblets/extensions/manager.py", line 467, in _load_extensions
   ext_class.info = ExtensionInfo(entrypoint, ext_class)

 File "/usr/lib/python2.7/site-packages/djblets/extensions/extension.py", line 186, in **init**
   key, value = line.split(": ", 1)

ValueError: need more than 1 value to unpack

**Comment by iconoeugen** [comment]
The problem is in @djblets

I opened an [issue](https://hellosplat.com/s/beanbag/tickets/4196/) and submitted a [fix](https://reviews.reviewboard.org/r/8001/) to it.

**Comment by vladsf** [comment]
Thank you!
